"use client";
import{useEffect,useMemo,useState}from"react";
const experience=[
{company:"Sprouts AI",role:"Software Engineer · Apple Platforms & System Software",place:"Chicago, IL",date:"Mar 2025 — Present",bullets:[
"Cut customer drop-off during first-run setup and onboarding flows by 30% by designing SwiftUI configuration, authentication, and deep-link experiences with Swift concurrency, making user-centric product decisions with design and product partners.",
"Reduced integration complexity 40% by architecting well-abstracted platform APIs and a typed URLSession networking layer (Codable, retries, caching, offline support) with clear separation of concerns between Swift clients and FastAPI services.",
"Achieved 99.95% availability for 1K+ daily active users by engineering reasonable failure modes end to end: graceful recovery from intermittent network failures on-device plus circuit breakers and graceful degradation in backend services.",
"Reduced production incidents 35% and lifted velocity 25% by leading technical design and code review standards for a 5-person team, mentoring 2 junior engineers, and modeling what good looks like in code and documentation.",
"Ensured quality at every step by owning XCTest/XCUITest coverage, Instruments profiling, and CI/CD automation of builds, tests, signing, and TestFlight distribution through App Store release."
]},
{company:"Resilience Inc",role:"Software Engineer · iOS & Platform APIs",place:"Chicago, IL",date:"Aug 2023 — Mar 2025",bullets:[
"Boosted student engagement 40% by shipping the Selena iOS app (Swift, UIKit/SwiftUI, MVVM with coordinators) to 10K+ students, making high-quality, user-centric product decisions validated with educators and designers.",
"Reduced bug density 30% by structuring the client into well-abstracted, protocol-oriented modules with dependency injection, and by designing clean REST/GraphQL platform APIs consumed across the Swift client and Python backend.",
"Delivered reliable experiences across devices and OS versions by implementing push notifications, universal links, Core Data offline sync, Keychain-backed authentication, and state restoration.",
"Accelerated junior engineer ramp-up 50% by establishing platform API design patterns and coding standards, and mentoring 3 junior engineers through pair programming and rigorous code reviews.",
"Cut rollback incidents 45% by automating CI/CD for build, XCTest/XCUITest, code signing, and phased TestFlight/App Store Connect releases alongside zero-downtime backend deployments."
]},
{company:"Tata Steel",role:"Software Engineer · Apple Platforms & Backend",place:"",date:"Apr 2018 — Aug 2023",bullets:[
"Modernized established Objective-C applications without disrupting production by incrementally introducing Swift modules via bridging headers and @objc interop, preserving API and binary compatibility across supported OS versions.",
"Improved API response times 40% and sustained 99.99% uptime for platforms serving 5K+ users by architecting cloud-native Java and Python microservices with well-abstracted platform APIs.",
"Reduced manual processing time 60% for IRIS and Coaching workflows by leading a 4-person cross-functional team through the full SDLC, coordinating releases with product, QA, security, and design, and mentoring junior developers.",
"Eliminated recurring crashes and performance regressions by debugging memory leaks, retain cycles, and race conditions with LLDB and Instruments, and enforcing main-thread hygiene with GCD and operation queues.",
"Cut infrastructure costs 35% by evaluating monolith vs. microservices tradeoffs, documenting the rationale, and influencing leadership to adopt cloud-native architecture patterns."
]}
];
const projects=[
["Pitch Perfect","Native iOS audio app with UIKit, AVFoundation, navigation, delegation, and Auto Layout.","Apple","https://github.com/devthedevil/Pitch_Perfect","https://github.com/devthedevil/Pitch_Perfect#readme"],
["oxide-hv","Memory-safe concurrent system software in Rust with cross-platform concerns.","Systems","https://github.com/devthedevil/oxide-hv","https://oxide-hv.vercel.app/"],
["Experimental Operating System","A UNIX-like kernel exploring processes, memory, files, and system calls.","Systems","https://github.com/devthedevil/EXPOS","https://github.com/devthedevil/EXPOS#readme"],
["Character Device Driver","Linux kernel interface connecting low-level I/O with user-space contracts.","Systems","https://github.com/devthedevil/Character-Device-Driver","https://github.com/devthedevil/Character-Device-Driver#readme"],
["16-Bit RISC Processor","Instruction design traced through a working datapath and hardware interface.","Systems","https://github.com/devthedevil/Hardware-lab","https://github.com/devthedevil/Hardware-lab#readme"],
["Real-time Stock Pipeline","Kafka and cloud pipeline engineered for reliable event movement and observability.","Data","https://github.com/devthedevil/Realtime-Stock-Market-Analysis","https://github.com/devthedevil/Realtime-Stock-Market-Analysis#readme"],
["CME MDP 3.0 Feed Handler","High-throughput multicast software with ordering and latency constraints.","Systems","https://github.com/devthedevil/CME-Multicast-Market-Data-Feed-Handler-C-","https://github.com/devthedevil/CME-Multicast-Market-Data-Feed-Handler-C-#readme"],
["TradeSentinel","Responsive market intelligence product with live decision workflows.","Product","https://github.com/devthedevil/tradesentinel","https://tradesentinel.vercel.app/"],
["AskMyStore","LangGraph retail assistant delivering contextual multi-step experiences.","AI","https://github.com/devthedevil/AskMyStore","https://ask-my-store.vercel.app/"],
["AgentFlow","Agent orchestration with tools, retrieval, memory, and guarded execution.","AI","https://github.com/devthedevil/openAI-Agent-SDK","https://github.com/devthedevil/openAI-Agent-SDK#readme"],
["LangChain Search","Search-grounded conversational AI connected to retrieved context.","AI","https://github.com/devthedevil/LangChain-Chat-with-Search","https://github.com/devthedevil/LangChain-Chat-with-Search#readme"],
["STRANGERS","Interactive React storytelling with responsive navigation and state.","Product","https://github.com/devthedevil/Strangers","https://strangers-react.vercel.app/"],
["HireLoop","Hiring workflow product focused on clear user journeys and decisions.","Product","https://github.com/devthedevil/hireloop","https://github.com/devthedevil/hireloop#readme"],
["Model Context Protocol","Structured tool and context integration experiments.","AI","https://github.com/devthedevil/MCP","https://github.com/devthedevil/MCP#readme"],
["Voting App on Kubernetes","Multi-service system deployed through container orchestration.","Cloud","https://github.com/devthedevil/Kubernetes-K8","https://github.com/devthedevil/Kubernetes-K8#readme"],
["Tic Tac Toe","Native Android interaction and state in a compact mobile application.","Mobile","https://github.com/devthedevil/TicTacToe-Game","https://github.com/devthedevil/TicTacToe-Game#readme"]
];
const phrases=["a trusted first run","graceful recovery","interfaces that endure","quality at every step"];
const stack=["Swift","Objective-C","SwiftUI","UIKit","AppKit","Cocoa","async/await","Actors","GCD","Core Data","Keychain","URLSession","XCTest","XCUITest","Instruments","LLDB","TestFlight","Platform APIs","FastAPI","Kubernetes"];
export default function Home(){const[phrase,setPhrase]=useState(0);const[filter,setFilter]=useState("All");useEffect(()=>{const t=setInterval(()=>setPhrase(p=>(p+1)%phrases.length),2200);return()=>clearInterval(t)},[]);const shown=useMemo(()=>filter==="All"?projects:projects.filter(p=>p[2]===filter),[filter]);return <main>
<nav><a className="brand" href="#top"><span>DK</span><b>SYSTEM / EXPERIENCE</b></a><div><a href="#journey">Journey</a><a href="#experience">Experience</a><a href="#projects">Work</a></div><a className="navcta" href="mailto:devkumar.dklv@gmail.com">CONNECT ↗</a></nav>
<section className="hero" id="top"><div className="grid"/><div className="hero-copy"><p className="eyebrow"><i/> APPLE PLATFORMS · SYSTEM SOFTWARE</p><h1>The first moment<br/><em>sets the standard.</em></h1><p className="dynamic">Engineering <span key={phrase}>{phrases[phrase]}</span></p><p className="lede">I build the systems behind a seamless beginning—clear interfaces, resilient state, thoughtful recovery, and carefully shipped experiences that help people feel at home from the first tap.</p><div className="actions"><a className="primary" href="#journey">Begin the journey <span>↓</span></a><a href="mailto:devkumar.dklv@gmail.com">devkumar.dklv@gmail.com ↗</a></div></div>
<div className="setup" aria-label="Animated device setup journey diagram"><div className="setup-head"><span>SETUP SESSION / 8B42</span><b><i/> ACTIVE</b></div><div className="device"><div className="island"/><span>HELLO</span><small>Swipe up to begin</small><i/></div><div className="steps"><div className="done"><i/>LANGUAGE <b>✓</b></div><div className="done"><i/>NETWORK <b>✓</b></div><div className="active"><i/>AUTHENTICATE <b>•••</b></div><div><i/>TRANSFER <b>04</b></div><div><i/>READY <b>05</b></div></div><div className="recovery"><small>FAILURE MODE</small><b>network interrupted</b><span>state preserved · retry safe ✓</span></div><div className="setup-foot"><span>DEVICE / iPHONE</span><span>STATE / 03 OF 05</span><span>QUALITY / GREEN</span></div></div>
<div className="stats"><div><b>30%</b><span>LESS SETUP DROP-OFF</span></div><div><b>10K+</b><span>MOBILE CUSTOMERS</span></div><div><b>99.95%</b><span>EXPERIENCE AVAILABILITY</span></div><div><b>45%</b><span>FEWER ROLLBACKS</span></div></div></section>

<section className="journey" id="journey"><header><div><p className="kicker">01 / FIRST-RUN JOURNEY</p><h2>Simple on the surface.<br/><em>Rigorous underneath.</em></h2></div><p>A great setup flow coordinates identity, connectivity, data, state, hardware, services, and recovery—without making any of that complexity the customer’s problem.</p></header><div className="journeyflow">{[["01","WELCOME","orient · localize"],["02","CONNECT","discover · retry"],["03","TRUST","authenticate · protect"],["04","TRANSFER","migrate · restore"],["05","PERSONALIZE","configure · notify"],["06","READY","verify · delight"]].map((x,i)=><div key={x[1]}><span>{x[0]}</span><i/><b>{x[1]}</b><small>{x[2]}</small>{i<5&&<em>→</em>}</div>)}</div><div className="principles"><article><span>01</span><h3>Design every failure mode</h3><p>Intermittent networks, interrupted authentication, partial state, and service degradation all deserve a calm path forward.</p></article><article><span>02</span><h3>Make interfaces outlive features</h3><p>Separation of concerns, protocol-oriented boundaries, and typed contracts keep complex systems changeable.</p></article><article><span>03</span><h3>Raise the standard together</h3><p>Architecture, reviews, tests, documentation, and mentorship compound into software—and teams—that improve every release.</p></article></div></section>

<section className="experience" id="experience"><header><p className="kicker">02 / EXPERIENCE</p><h2>Built for people.<br/><em>Owned end to end.</em></h2></header><div className="timeline">{experience.map((job,j)=><article key={job.company}><div className="job"><span>0{j+1}</span><div><h3>{job.company}</h3><p>{job.role}</p></div><div><b>{job.date}</b><small>{job.place}</small></div></div><ol>{job.bullets.map((b,i)=><li key={b}><span>{String(i+1).padStart(2,"0")}</span><p>{b}</p></li>)}</ol></article>)}</div></section>

<section className="architecture"><div><p className="kicker">03 / PLATFORM ARCHITECTURE</p><h2>Boundaries that<br/><em>make change safe.</em></h2><p>Clean architecture is not abstraction for its own sake. It localizes risk, clarifies ownership, and creates space for new experiences.</p></div><div className="layers"><div><span>EXPERIENCE</span><b>SwiftUI · UIKit · AppKit</b></div><i>↓ user intent</i><div><span>DOMAIN</span><b>State · Coordinators · Protocols</b></div><i>↓ typed contracts</i><div><span>PLATFORM</span><b>URLSession · Core Data · Keychain</b></div><i>↓ resilient services</i><div><span>BACKEND</span><b>APIs · Auth · Observability</b></div></div></section>

<section className="projects" id="projects"><header><div><p className="kicker">04 / ENGINEERING LAB</p><h2>Understand every<br/><em>layer you depend on.</em></h2></div><p>Native mobile, systems software, drivers, data pipelines, cloud platforms, and AI agents—each project sharpens the judgment needed to design across boundaries.</p></header><div className="filters">{["All","Apple","Systems","Data","AI","Product","Cloud","Mobile"].map(f=><button key={f} className={filter===f?"active":""} onClick={()=>setFilter(f)}>{f}</button>)}</div><div className="cards">{shown.map((p,i)=><article key={p[0]}><div className="cardhead"><span>{String(i+1).padStart(2,"0")}</span><b>{p[2]}</b></div><div className="wire"><i/><i/><i/><i/><span/></div><h3>{p[0]}</h3><p>{p[1]}</p><div className="links"><a href={p[3]} target="_blank" rel="noreferrer">Source code ↗</a><a href={p[4]} target="_blank" rel="noreferrer">{p[4].includes("#readme")?"Technical demo":"Live demo"} ↗</a></div></article>)}</div></section>

<section className="toolkit"><p className="kicker">05 / TOOLKIT</p><div className="ticker"><div>{[...stack,...stack].map((x,i)=><span key={i}>{x}<i>●</i></span>)}</div></div><div className="toolgrid"><article><span>CLIENT</span><h3>Native by instinct</h3><p>Swift, Objective-C, SwiftUI, UIKit, AppKit, Auto Layout, MVVM, coordinators, state restoration and accessibility-minded UI.</p></article><article><span>PLATFORM</span><h3>Reliable through change</h3><p>Concurrency, protocols, dependency injection, Core Data, Keychain, URLSession, offline sync, universal links and push notifications.</p></article><article><span>QUALITY</span><h3>Confidence in every release</h3><p>XCTest, XCUITest, Instruments, LLDB, profiling, code review, CI/CD, signing, TestFlight, phased release and production monitoring.</p></article></div></section>

<section className="research"><div><p className="kicker">06 / RESEARCH</p><h2>Evidence before<br/><em>assumption.</em></h2><p>Research and system design share the same habit: make tradeoffs explicit, test them honestly, and preserve the reasoning behind the decision.</p></div><article><span>IEEE PUBLICATION</span><h3>Comparative Study of Movie Recommendation Systems using Feature Engineering</h3><div className="researchviz"><i/><i/><i/><i/><b>MEASURE / COMPARE</b></div><div><a href="https://ieeexplore.ieee.org/document/10094480" target="_blank" rel="noreferrer">Paper ↗</a><a href="https://github.com/devthedevil/Comparative-Study-of-Movie-Recommendation-System/blob/main/Netflix_Movie.ipynb" target="_blank" rel="noreferrer">Source ↗</a><a href="https://drive.google.com/file/d/1rayr6Cht6quyLUJOXWOAcBi_rxQp2Ol0/view" target="_blank" rel="noreferrer">Certificate ↗</a></div></article></section>

<section className="contact"><p className="kicker"><i/> READY FOR WHAT COMES FIRST</p><h2>Make the first<br/><em>experience unforgettable.</em></h2><p>I care about the details that help technology disappear: the transition that feels inevitable, the recovery path that feels reassuring, and the architecture that lets the next idea arrive safely.</p><a className="primary" href="mailto:devkumar.dklv@gmail.com">Start a conversation <span>↗</span></a><div><a href="https://github.com/devthedevil" target="_blank" rel="noreferrer">GitHub ↗</a><a href="https://leetcode.com/u/dev_kumar_dklv/" target="_blank" rel="noreferrer">LeetCode ↗</a><a href="tel:+13125328223">+1 312 532 8223</a></div></section>
</main>}
